title: Dataset with Probabilities of Inflation Disasters from Options Prices
description: Download the dataset and view figures that use it
baseurl: "/web-inflationdisasters" 
url: "https://R2RsquaredLSE.github.io"
github_username: R2RsquaredLSE

theme: jekyll-theme-cayman
